all: extension

target=LuceneComponent.dll

commonInclude=./../../../../Common/include/
commonLib=./../../../../Common/lib/

src=Extension.cpp Extension.h

lib=-lFlashRuntimeExtensions -llibclucene-core -llibclucene-shared -L$(commonLib)

inc=-I$(commonInclude) -I$(CLUCENE)\src\core\ -I$(CLUCENE)\src\shared\

flags=-Wall -shared -static-libgcc -static-libstdc++

extension: $(src)
	g++ $(flags) $(src) $(lib) $(inc) -o ./../bin/$(target)